### ISSUE TITLE
在MIUI14（A13）下点击特定功能会闪退

### ISSUE THREAD

**Issue by Dev-Apricity** [Kyant0/MusicYou#1]
在MIUI14下点击个性化选项会闪退，该问题可稳定复现

**Comment by Dev-Apricity** [comment]
![Screenshot_2023-01-29-07-05-08-740_com miui thirdappassistant](https://user-images.githubusercontent.com/87255799/215295451-120b8d3a-4ec7-4ccc-a2b1-02c77653d6ec.jpg)
![Screenshot_2023-01-29-07-05-15-658_com kyant musicyou](https://user-images.githubusercontent.com/87255799/215295454-b78e45c3-f82e-4e47-825b-0924ac2c89ab.jpg)

**Comment by Dev-Apricity** [comment]
如果开发者需要可以联系我抓取日志
3239691043@qq.com

**Comment by Dev-Apricity** [comment]
java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/customization } cannot be found in the navigation graph v(0x0) startDestination={a(0x78d845ec) route=home}
	at u4.y.i(Unknown Source:111)
	at d6.t0.a(Unknown Source:35)
	at d6.t0.j(Unknown Source:12)
	at l.z.a(Unknown Source:18)
	at l.z.e(Unknown Source:12)
	at m.e2.h(Unknown Source:123)
	at e8.a.o(Unknown Source:7)
	at k8.h.o0(Unknown Source:75)
	at kotlinx.coroutines.k.n(Unknown Source:128)
	at kotlinx.coroutines.k.A(Unknown Source:43)
	at kotlinx.coroutines.k.B(Unknown Source:1)
	at kotlinx.coroutines.k.o(Unknown Source:15)
	at c1.e0.j(Unknown Source:57)
	at h1.f.m(Unknown Source:19)
	at c1.g.e(Unknown Source:92)
	at c1.g.e(Unknown Source:78)
	at c1.g.e(Unknown Source:78)
	at c1.g.e(Unknown Source:78)
	at c1.g.e(Unknown Source:78)
	at c1.g.e(Unknown Source:78)
	at c1.h.e(Unknown Source:30)
	at android.support.v4.media.k.i(Unknown Source:28)
	at y.z.a(Unknown Source:183)
	at androidx.compose.ui.platform.AndroidComposeView.z(Unknown Source:77)
	at androidx.compose.ui.platform.AndroidComposeView.g(Unknown Source:220)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:87)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4403)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
	at android.view.View.dispatchPointerEvent(View.java:15330)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6943)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6730)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6149)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6206)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6337)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6180)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6394)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6153)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6206)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6180)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6153)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9291)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9242)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9210)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9430)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:292)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: k5.e: [androidx.compose.ui.platform.l1@5bdbc59, b0.e@702801e, v1{Cancelling}@44de0ff, l0@3f0aecc]

**Comment by Kyant0** [comment]
界面没有做，不是bug
